# Generated by Django 4.2.10 on 2024-02-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthhomeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credential',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
