# Generated by Django 4.2.10 on 2024-02-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthhomeapi', '0004_alter_user_admin_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
