# Generated by Django 4.2.10 on 2024-02-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthhomeapi', '0005_rename_receiver_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
