# Generated by Django 4.2.10 on 2024-02-23 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthhomeapi', '0007_conversation_message_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
    ]
