# Generated by Django 4.2.10 on 2024-03-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthhomeapi', '0010_alter_message_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('route', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
