# Generated by Django 4.2.10 on 2024-03-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthhomeapi', '0011_dbmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('route', models.CharField(default='', max_length=200)),
                ('dose', models.CharField(default='', max_length=200)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_medications', to='healthhomeapi.user')),
            ],
        ),
    ]
